version: '3.3'
services:
  web:
    container_name: todoapp_web
    build:
      context: ./web
      dockerfile: Dockerfile
    #tty: true
    volumes:
      - ../app:/var/www/app
    working_dir: /var/www/app/todoapp
    ports:
      - 8080:80
      - 8000:8000
      #restart: always

  db:
    container_name: todoapp_postgres
    image: postgres:12.3
    #build:
      #context: ./docker/mysql
      #dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      # 設定ファイル
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      # データベースのデータ
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    #restart: always
